### ISSUE TITLE
Deleting a component will remove strike through from all the components

### ISSUE THREAD

**Issue by mozCheese** [mozCheese/To-Do-App#2]
Whenever we delete something from the list it will rewrite the whole UI but strike through list component not able to retain themselves.

**Comment by Ayushak18** [comment]
I am working on it.
I made the list persists but not able to reflect that in UI.
I will try to find a way to do so.

**Comment by mozCheese** [comment]
Ayush has done a fab job by solving this issue.
Amazing work.
